### ISSUE TITLE
Problems with nginx config

### ISSUE THREAD

**Issue by ctrlcctrlv** [infinity-next/infinity-next#116]
* [ ] uses `if` instead of `try_files` http://wiki.nginx.org/IfIsEvil
* [ ] unprofessional comments with meme faces `:^)`
* [ ] might need notes on what to do if there are a different number of subdirectories?

**Comment by ctrlcctrlv** [comment]
reference #114 and @majestrate

**Comment by jaw-sh** [comment]
To reiterate, I'm going to end up deleting the contrib directory and moving this as documentation on the github wiki or something more organized. But please work in that file now. If nothing is done in the next few days and/or I don't know if anyone is working on it I will do it myself and create similar documents for apache and lighttpd.

**Comment by ctrlcctrlv** [comment]
Working on this now, just mentioning another problem:

[x] declares `root` twice

**Comment by rajlaksh** [comment]
Here is Complete Laravel Config for Nginx

`server {`
`listen 80;`
`server_name 	example.com;`

`root 			/var/www/public;`
`index 			index.php index.htm index.html;`

`location / {`
`try_files $uri $uri/ /index.php?$query_string;`
`}`

`location ~ .php$ {`
`fastcgi_pass 127.0.0.1:9000;`
`fastcgi_index index.php;`
`fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;`
`include fastcgi_params;`
`}`

`}`

Remove Document Root because it will cause Errors.

**Comment by rajlaksh** [comment]
when i give it JPEG file to upload it does not pick it but it picks JPG

Everything is Okay with Nginx my config work like i said.

Demo

![book](https://cloud.githubusercontent.com/assets/8939005/10416000/694e6afc-7020-11e5-86bc-1cba138db5d1.png)

**Comment by jaw-sh** [comment]
JPG and JPEG are functionally identical. The file uploader corrects 
extensions. This is by design.
